blank_issues_enabled: false
contact_links:
  - name: 'Questions'
    url: https://github.com/tu2-atmanand/obsidian-library-plugin/discussions
    about: 'Ask questions or browse the past questions on GitHub Discussions.'
#   - name: 'Contribute to the docs'
#     url: https://github.com/RyotaUshio/obsidian-pdf-plus/tree/docs
#     about: 'Improve the documentation to help the community.'
