name: Feature request
description: "Suggest an idea to enhance the functionality of Library plugin."
labels: ["enhancement"]
title: "[FR] "
body:
  - type: markdown
    attributes:
      value: |
        Note: for the time being, it is unlikely that Library plugin will support handwritten annotation. [Learn more](https://github.com/RyotaUshio/obsidian-pdf-plus/discussions/42)
  - type: textarea
    id: description
    attributes:
      label: Describe your request
      description: 'A clear and detailed description of the feature you want to have.'
      placeholder: 'Explain your request by elaborating it properly and possible with images if you like to add.'
    validations:
      required: true
